import type { Metadata } from "next";
import "./globals.css";
import { neueRegrade } from "@/lib/fonts";
import { Providers } from "@/components/providers/providers";

export const metadata: Metadata = {
    title: "TypingTiger",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={neueRegrade.className}
            suppressHydrationWarning
        >
            <body suppressHydrationWarning>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
