import type { Metadata } from "next";
import "./globals.css";
import { neueRegrade } from "@/lib/fonts";
import { Providers } from "@/providers/providers";

import Header from "@/app/components/Header";

export const metadata: Metadata = {
    title: "TypingTiger",

    description: "Generated by create next app",
    icons: {
        icon: [
            {
                url: "/favicon.ico", // /public path
                href: "/favicon.ico", // /public path
            },
        ],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={neueRegrade.className}
            suppressHydrationWarning
        >
            <body suppressHydrationWarning>
                <Providers>
                    <Header />

                    {children}
                </Providers>
            </body>
        </html>
    );
}
